; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-c3

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
board_build.partitions = partitions.csv
build_src_filter = +<main.cpp>
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	h2zero/NimBLE-Arduino @ ^1.4.2
	adafruit/Adafruit Fingerprint Sensor Library@^2.1.4
	bblanchon/ArduinoJson @ ^6.21.4
	fbiego/ESP32Time @ ^2.0.6

[env:test-r503]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
build_src_filter = +<../test/test_r503/test_r503.cpp>
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = adafruit/Adafruit Fingerprint Sensor Library@^2.1.4

[env:test-tzm1026]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
build_src_filter = +<../test/test_tzm1026/test_tzm1026.cpp>
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

